---
title: "Sep 18 Data manipulation"
output: github_document
---

```{r}
library(tidyverse)
```

Let's import datasets

```{r}
litters_df=
  read_csv("data_import_examples/FAS_litters.csv", na = c("NA", ".", ""))
litters_df = 
  janitor::clean_names(litters_df)
```

```{r}
Pups_df = 
    read_csv(
        file = "data_import_examples/FAS_pups.csv",
        skip = 3,
        na = c("NA", ".", ""))

Pups_df = 
  janitor::clean_names(Pups_df)
```

## select

'select' select variables from my data frame
select specific variables

```{r}
select(litters_df, group, litter_number, gd0_weight)
```

select range

```{r}
select(litters_df, group:gd_of_birth)
```

select by removal

```{r}
select(litters_df, -group)
select(litters_df, -(group:gd_of_birth))
```

select by prefix
```{r}
select(litters_df, group, starts_with("gd"))
```

rearrange by selecting
```{r}
select(litters_df, starts_with("gd"), group)
select(litters_df, litter_number, everything())

relocate(litters_df, litter_number)
```

rename by selecting

```{r}
select(litters_df, GROUP= group, everything())
rename(litters_df, GROUP= group)
```

what if i only select one variable

```{r}
select(litters_df , group)

pull(litters_df, group)
litters_df$group
```

LA code:

```{r}
select(Pups_df,litter_number, sex, pd_ears)
```


## 'filter'

use 'filter()' to filter out rows

```{r}
filter(litters_df, gd_of_birth == 20)
```





















