---
title: "Import Data"
output: github_document
---

```{r}
library(tidyverse)
library(readxl)
library(haven)
```

Let's import data

```{r}
litters_df=
  read_csv("data_import_examples/FAS_litters.csv")
```

Look at your data

```{r}
names(litters_df)
```

Update names in "litters_df"

```{r}
litters_df = 
  janitor::clean_names(litters_df)
```

Look at the data!

```{r}
litters_df
```

Is the data clean?

```{r}
skimr::skim(litters_df)
```

#Fix the missingness

```{r}
litters_df =
  read_csv("data_import_examples/FAS_litters.csv", na =c("NA",".",""))
```



#Import Pups Data

```{r}
Pups_df = 
    read_csv(
        file = "data_import_examples/FAS_pups.csv",
        skip = 3,
        na = c("NA", ".", ""))

Pups_df = 
  janitor::clean_names(Pups_df)
```

#Okay what about excel

CSVs are really great!
Sometimes I only have excel files...

```{r}
mlb_df=
  read_excel("data_import_examples/mlb11.xlsx")
```

Import LotR words count...

```{r}
lotr_df = read_excel(
  "data_import_examples/LotR_Words.xlsx",
  range = "B3:D6"
)
```

#SAS?!

Import the PULSE data

```{r}
pulse_df=("data_import_examples/public_pulse_data.sas7bdat")

pulse_df = 
  janitor::clean_names(pulse_df)
```



#Why do I hate read.csv so much?

```{r}
litters_df_base =
  read.csv("data_import_examples/FAS_litters.csv")
```

#What about data exporting

```{r}
write_csv(lotr_df,"lotr_df.csv")
```

